// client/src/components/Transcript.vue
<template>
  <div
    class="pointer-events-none absolute inset-x-0 bottom-32 flex flex-col items-center gap-1 px-6 text-center"
  >
    <div
      v-for="msg in visibleMessages"
      :key="msg.id"
      class="max-w-xl rounded-full px-4 py-1.5 text-sm backdrop-blur-md"
      :class="
        msg.role === 'user'
          ? 'bg-sky-500/15 text-sky-100'
          : 'bg-white/10 text-neutral-100'
      "
    >
      {{ msg.text }}
      <span v-if="!msg.done" class="ml-1 animate-pulse">▍</span>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { useTalkStore } from "@/lib/store";

const store = useTalkStore();
const visibleMessages = computed(() =>
  store.messages.filter((m) => m.text.trim() || !m.done).slice(-3),
);
</script>

// src/components/Transcript.tsx
"use client";

import { useEffect, useRef } from "react";
import { useTalkStore } from "@/lib/store";

export function Transcript() {
  const messages = useTalkStore((s) => s.messages);
  const scroller = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const el = scroller.current;
    if (el) el.scrollTop = el.scrollHeight;
  }, [messages]);

  if (messages.length === 0) return null;

  return (
    <div
      ref={scroller}
      className="pointer-events-auto absolute inset-x-0 bottom-40 mx-auto flex max-h-52 w-full max-w-2xl flex-col gap-3 overflow-y-auto px-6 [mask-image:linear-gradient(to_bottom,transparent,black_18%)]"
    >
      {messages.map((m) => (
        <div
          key={m.id}
          className={
            m.role === "assistant"
              ? "text-balance text-lg leading-snug text-neutral-100"
              : "text-sm text-neutral-500"
          }
        >
          {m.role === "user" && <span className="mr-2 text-neutral-600">you</span>}
          {m.text}
        </div>
      ))}
    </div>
  );
}
